### ISSUE TITLE
Shouldn't all integers be string

### ISSUE THREAD

**Issue by noonien** [jon4hz/go-1inch#1]
<https://github.com/jon4hz/go-1inch/blob/master/go1inch_types.go#L17> seems to be a string

**Comment by jon4hz** [comment]
That is very possible. I'll have to check it out later. It's a bit odd since their docs don't match the swagger specs and I realized that a bit to late...

**Comment by jon4hz** [comment]
e5cc5a71b65b81831c0d9c434cb9eb85594a7bc5 Should fix it. Next to that I made all required fields a parameter and added a struct for optional values. Both will be in the next release.
